# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
#
# Optional
# Default: ["http"]
#
defaultEntryPoints = ["http"]

# Entrypoints definition
#
# Optional
# Default:
[entryPoints]
    [entryPoints.http]
    address = "{{ traefik_bind_ip }}:80"
    [entryPoints.traefik]
    address = "{{ traefik_bind_ip }}:8081"

logLevel = "INFO"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "consul"
watch = true

[consul]
endpoint = "{{ traefik_consul_master }}:8500"
watch = true
prefix = "traefik"

[consulCatalog]
endpoint = "{{ traefik_consul_master }}:8500"
domain = "service.consul"
exposedByDefault = true
prefix = "traefik"

# Activate API and Dashboard
[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
